<a href="https://colab.research.google.com/github/Overleaff/ChatBox-using-Big-Bird-/blob/main/QuestionAnswering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture
!pip install transformers
!pip install tensorflow

In [ ]:
from transformers import BigBirdForQuestionAnswering
from transformers import AutoTokenizer

model_id = "deepset/bert-base-cased-squad2"
model = BigBirdForQuestionAnswering.from_pretrained(model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)

Downloading:   0%|          | 0.00/508 [00:00<?, ?B/s]

You are using a model of type bert to instantiate a model of type big_bird. This is not supported for all configurations of models and can yield errors.


Downloading:   0%|          | 0.00/413M [00:00<?, ?B/s]

Some weights of the model checkpoint at deepset/bert-base-cased-squad2 were not used when initializing BigBirdForQuestionAnswering: ['bert.pooler.dense.bias', 'qa_outputs.bias', 'bert.pooler.dense.weight', 'qa_outputs.weight']
- This IS expected if you are initializing BigBirdForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BigBirdForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BigBirdForQuestionAnswering were not initialized from the model checkpoint at deepset/bert-base-cased-squad2 and are newly initialized: ['qa_classifier.qa_outputs.bias', 'qa_classifier.intermediate.dense.weight', 'qa_classifier.output.LayerNorm.weight', 'qa_classifier

Downloading:   0%|          | 0.00/152 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
context = ("Globally, as of 3:28pm CET, 8 November 2021, there have been 249743428 confirmed cases of COVID-19, including 5047652 deaths, reported to WHO."
" As of 7 November 2021, a total of 7084921786 vaccine doses have been administered."
)
context

'Globally, as of 3:28pm CET, 8 November 2021, there have been 249743428 confirmed cases of COVID-19, including 5047652 deaths, reported to WHO. As of 7 November 2021, a total of 7084921786 vaccine doses have been administered.'

In [ ]:
question = [
          "How many cases of COVID-19",
          "how many vaccine doses have been administered in total"
]

My question : 
         

1.  "How many COVID-19 cases",
2.   "How many vaccine doses have been administered in total"


---


My context :
"Globally, as of 3:28pm CET, 8 November 2021, there have been 249743428 confirmed cases of COVID-19, including 5047652 deaths, reported to WHO."
" As of 7 November 2021, a total of 7084921786 vaccine doses have been administered "



In [ ]:
from transformers import pipeline
tokenizer.encode(question[1], truncation = True, padding = True)

nlp = pipeline ('question-answering', model= model, tokenizer= tokenizer)

# Passing the Question and Context into the QA pipeline
output = nlp(question = question[1], context = context)

# Printing the Output
print(output)


{'score': 0.0007909336127340794, 'start': 141, 'end': 167, 'answer': '. As of 7 November 2021, a'}
